services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Dispatcher\Subscriber\AppLifecycleSubscriber:
    tags:
      - { name: 'kernel.dispatcher' }

  App\Dispatcher\Subscriber\WindowEventsSubscriber:
    tags:
      - { name: 'kernel.dispatcher' }

  App\Dispatcher\Subscriber\ControllerLoggerSubscriber:
    tags:
      - { name: 'kernel.dispatcher' }
