services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: '%debug%'

  Bic\Renderer\RendererInterface:
    class: App\Renderer
    public: true

  App\Renderer:
    alias: 'Bic\Renderer\RendererInterface'
    public: true

